apiVersion: mysql.radondb.com/v1alpha1
kind: Backup
metadata:
  name: backup-mysql
spec:
  # Add fields here
  image: radondb/mysql57-sidecar:v2.2.1
  # hostname if empty, use the leader as hostname
  hostName: mysql-cluster-mysql-0
  clusterName: host
  # nfsServerAddress: ""
